server:
  port: 8888

spring:
  profiles:
    active: dev
  application:
    name: API-GATEWAY
  config:

    import: optional:configserver:http://config-server:8763 #docker
#    import: optional:configserver:http://localhost:8763 #localhost
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**,/api/admin/**,/api/user/**

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka